// Generated by scripts/social/generate.mjs. Do not edit by hand.
// Run `pnpm social:build` to regenerate.

export type SocialRendition = {
  sizeId: string;
  label: string;
  width: number;
  height: number;
  png: string;
  jpg: string;
  mp4: string;
  pngBytes: number;
  jpgBytes: number;
  mp4Bytes: number;
};

export type SocialPost = {
  id: string;
  title: string;
  note: string;
  headline: string;
  renditions: SocialRendition[];
};

export const MOTION_SECONDS = 6;

export const SOCIAL_POSTS: SocialPost[] = [
  {
    "id": "01-architect",
    "title": "The architect",
    "note": "Opens on the money and lands on the person. The attack is the reason to keep reading, and the engineer who saw it coming is the reason the book is not another Wall Street thriller.",
    "headline": "Four trillion dollars are frozen. One engineer saw it coming.",
    "renditions": [
      {
        "sizeId": "4x5",
        "label": "Vertical feed",
        "width": 1080,
        "height": 1350,
        "png": "/social/01-architect-4x5.png?v=3e90f511",
        "jpg": "/social/01-architect-4x5.jpg?v=ccc8041e",
        "mp4": "/social/01-architect-4x5.mp4?v=f29c7a89",
        "pngBytes": 1987345,
        "jpgBytes": 517755,
        "mp4Bytes": 3057151
      },
      {
        "sizeId": "9x16",
        "label": "Story and Reel cover",
        "width": 1080,
        "height": 1920,
        "png": "/social/01-architect-9x16.png?v=c488bfa9",
        "jpg": "/social/01-architect-9x16.jpg?v=acc70d67",
        "mp4": "/social/01-architect-9x16.mp4?v=f5f8724d",
        "pngBytes": 2791563,
        "jpgBytes": 707037,
        "mp4Bytes": 4319123
      },
      {
        "sizeId": "1x1",
        "label": "Square feed",
        "width": 1080,
        "height": 1080,
        "png": "/social/01-architect-1x1.png?v=583f9bfd",
        "jpg": "/social/01-architect-1x1.jpg?v=7bfc5b30",
        "mp4": "/social/01-architect-1x1.mp4?v=3395e93a",
        "pngBytes": 1529245,
        "jpgBytes": 396847,
        "mp4Bytes": 2205266
      }
    ]
  },
  {
    "id": "02-praise",
    "title": "The review",
    "note": "Third-party proof. A verdict from a name a reader can go and check outranks anything the author says about his own book, so the quote takes the top of the frame.",
    "headline": "A brisk financial thriller buoyed by a powerful emotional throughline.",
    "renditions": [
      {
        "sizeId": "4x5",
        "label": "Vertical feed",
        "width": 1080,
        "height": 1350,
        "png": "/social/02-praise-4x5.png?v=db9d640e",
        "jpg": "/social/02-praise-4x5.jpg?v=92bb1db8",
        "mp4": "/social/02-praise-4x5.mp4?v=caf14347",
        "pngBytes": 1949445,
        "jpgBytes": 504744,
        "mp4Bytes": 2986310
      },
      {
        "sizeId": "9x16",
        "label": "Story and Reel cover",
        "width": 1080,
        "height": 1920,
        "png": "/social/02-praise-9x16.png?v=810e3099",
        "jpg": "/social/02-praise-9x16.jpg?v=07843e13",
        "mp4": "/social/02-praise-9x16.mp4?v=184c4c78",
        "pngBytes": 2761278,
        "jpgBytes": 694800,
        "mp4Bytes": 4399301
      },
      {
        "sizeId": "1x1",
        "label": "Square feed",
        "width": 1080,
        "height": 1080,
        "png": "/social/02-praise-1x1.png?v=46e72f04",
        "jpg": "/social/02-praise-1x1.jpg?v=9503270f",
        "mp4": "/social/02-praise-1x1.mp4?v=8ca5a245",
        "pngBytes": 1524694,
        "jpgBytes": 392221,
        "mp4Bytes": 2262389
      }
    ]
  },
  {
    "id": "03-timelines",
    "title": "The heist",
    "note": "The plot at its most propulsive. What is being stolen, what it costs, and the structure that makes this book different from every other Wall Street thriller.",
    "headline": "A high-tech bank heist. The world on the brink of war.",
    "renditions": [
      {
        "sizeId": "4x5",
        "label": "Vertical feed",
        "width": 1080,
        "height": 1350,
        "png": "/social/03-timelines-4x5.png?v=d76b754b",
        "jpg": "/social/03-timelines-4x5.jpg?v=e6890056",
        "mp4": "/social/03-timelines-4x5.mp4?v=a62f914c",
        "pngBytes": 1980357,
        "jpgBytes": 510294,
        "mp4Bytes": 3137605
      },
      {
        "sizeId": "9x16",
        "label": "Story and Reel cover",
        "width": 1080,
        "height": 1920,
        "png": "/social/03-timelines-9x16.png?v=be032557",
        "jpg": "/social/03-timelines-9x16.jpg?v=d0b92855",
        "mp4": "/social/03-timelines-9x16.mp4?v=a848d6d9",
        "pngBytes": 2783277,
        "jpgBytes": 699582,
        "mp4Bytes": 4262126
      },
      {
        "sizeId": "1x1",
        "label": "Square feed",
        "width": 1080,
        "height": 1080,
        "png": "/social/03-timelines-1x1.png?v=d5e1cf0c",
        "jpg": "/social/03-timelines-1x1.jpg?v=20a076ce",
        "mp4": "/social/03-timelines-1x1.mp4?v=85d29498",
        "pngBytes": 1522500,
        "jpgBytes": 392489,
        "mp4Bytes": 2250089
      }
    ]
  },
  {
    "id": "04-cipher",
    "title": "The cipher",
    "note": "The detail people repeat to each other. A failsafe hidden in a family recipe book, readable only by the children who lived those meals.",
    "headline": "The global financial system is under attack.",
    "renditions": [
      {
        "sizeId": "4x5",
        "label": "Vertical feed",
        "width": 1080,
        "height": 1350,
        "png": "/social/04-cipher-4x5.png?v=59857e3a",
        "jpg": "/social/04-cipher-4x5.jpg?v=f7fc30d7",
        "mp4": "/social/04-cipher-4x5.mp4?v=24e2a302",
        "pngBytes": 1961194,
        "jpgBytes": 505868,
        "mp4Bytes": 3103847
      },
      {
        "sizeId": "9x16",
        "label": "Story and Reel cover",
        "width": 1080,
        "height": 1920,
        "png": "/social/04-cipher-9x16.png?v=bfcde545",
        "jpg": "/social/04-cipher-9x16.jpg?v=81fc700a",
        "mp4": "/social/04-cipher-9x16.mp4?v=b1897a08",
        "pngBytes": 2757949,
        "jpgBytes": 694470,
        "mp4Bytes": 4017843
      },
      {
        "sizeId": "1x1",
        "label": "Square feed",
        "width": 1080,
        "height": 1080,
        "png": "/social/04-cipher-1x1.png?v=6633629d",
        "jpg": "/social/04-cipher-1x1.jpg?v=14217116",
        "mp4": "/social/04-cipher-1x1.mp4?v=1cf453ca",
        "pngBytes": 1505159,
        "jpgBytes": 388383,
        "mp4Bytes": 2185408
      }
    ]
  },
  {
    "id": "05-praise-midwest",
    "title": "The review, Midwest",
    "note": "The second verdict. Midwest Book Review reaches librarians and booksellers, so this one is worth running where a trade name carries more than a blurb does.",
    "headline": "Sridharan’s tense thriller will delight readers.",
    "renditions": [
      {
        "sizeId": "4x5",
        "label": "Vertical feed",
        "width": 1080,
        "height": 1350,
        "png": "/social/05-praise-midwest-4x5.png?v=6fc024c0",
        "jpg": "/social/05-praise-midwest-4x5.jpg?v=8bbded76",
        "mp4": "/social/05-praise-midwest-4x5.mp4?v=82c735d3",
        "pngBytes": 1945234,
        "jpgBytes": 495544,
        "mp4Bytes": 2921059
      },
      {
        "sizeId": "9x16",
        "label": "Story and Reel cover",
        "width": 1080,
        "height": 1920,
        "png": "/social/05-praise-midwest-9x16.png?v=2f855a2f",
        "jpg": "/social/05-praise-midwest-9x16.jpg?v=85e6bf24",
        "mp4": "/social/05-praise-midwest-9x16.mp4?v=a3564663",
        "pngBytes": 2754876,
        "jpgBytes": 683756,
        "mp4Bytes": 4353303
      },
      {
        "sizeId": "1x1",
        "label": "Square feed",
        "width": 1080,
        "height": 1080,
        "png": "/social/05-praise-midwest-1x1.png?v=e47abfad",
        "jpg": "/social/05-praise-midwest-1x1.jpg?v=821a2944",
        "mp4": "/social/05-praise-midwest-1x1.mp4?v=51518eef",
        "pngBytes": 1520962,
        "jpgBytes": 385108,
        "mp4Bytes": 2152961
      }
    ]
  },
  {
    "id": "06-praise-maturi",
    "title": "The review, Maturi",
    "note": "An author verdict rather than a trade one. It is the only review that names the South Indian material, which is the part of the book a trade review has no room for.",
    "headline": "Sridharan deftly and elegantly weaves rich details of South Indian life.",
    "renditions": [
      {
        "sizeId": "4x5",
        "label": "Vertical feed",
        "width": 1080,
        "height": 1350,
        "png": "/social/06-praise-maturi-4x5.png?v=590512a8",
        "jpg": "/social/06-praise-maturi-4x5.jpg?v=93b9f773",
        "mp4": "/social/06-praise-maturi-4x5.mp4?v=9037d323",
        "pngBytes": 1952713,
        "jpgBytes": 509406,
        "mp4Bytes": 2921781
      },
      {
        "sizeId": "9x16",
        "label": "Story and Reel cover",
        "width": 1080,
        "height": 1920,
        "png": "/social/06-praise-maturi-9x16.png?v=56e64b6c",
        "jpg": "/social/06-praise-maturi-9x16.jpg?v=d10c3476",
        "mp4": "/social/06-praise-maturi-9x16.mp4?v=5b9ce0a3",
        "pngBytes": 2764701,
        "jpgBytes": 699627,
        "mp4Bytes": 4271128
      },
      {
        "sizeId": "1x1",
        "label": "Square feed",
        "width": 1080,
        "height": 1080,
        "png": "/social/06-praise-maturi-1x1.png?v=0f613d20",
        "jpg": "/social/06-praise-maturi-1x1.jpg?v=72a92de4",
        "mp4": "/social/06-praise-maturi-1x1.mp4?v=5d5d3724",
        "pngBytes": 1526950,
        "jpgBytes": 395725,
        "mp4Bytes": 2167042
      }
    ]
  }
];
