/**
 * Renders the social post set to public/social.
 *
 * Each concept produces, at each size, a PNG master, a JPG for upload, and a
 * looping .mp4 of the glitch background running under the same composition.
 * Run with `pnpm social:build`, or pass a concept id fragment to redo one.
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { SIZES, seedFrom } from "./tokens.mjs";
import { CONCEPTS } from "./concepts.mjs";
import {
  PUBLIC_DIR,
  ROOT,
  documentFor,
  findChrome,
  shoot,
  toJpeg,
} from "./render.mjs";
import { MOTION, renderLoop } from "./motion.mjs";

const OUT_DIR = path.join(PUBLIC_DIR, "social");
const WORK_DIR = path.join(ROOT, "node_modules", ".cache", "social-posts");
const MANIFEST_PATH = path.join(ROOT, "src", "lib", "social-posts.generated.ts");

/**
 * Delete renders left behind by a concept or size that no longer exists, so
 * the directory and the manifest can never disagree.
 */
async function pruneStale(expected) {
  const existing = await readdir(OUT_DIR).catch(() => []);
  const stale = existing.filter(
    (name) => /\.(png|jpg|mov|mp4)$/.test(name) && !expected.has(name)
  );
  await Promise.all(stale.map((name) => rm(path.join(OUT_DIR, name))));
  return stale;
}

/**
 * Emit the manifest the /socials page renders from. Generating it keeps the
 * copy in `concepts.mjs` as the single source of truth, so a concept cannot be
 * added to the page without an image behind it.
 */
async function writeManifest(concepts) {
  const bytesOf = async (relative) =>
    stat(path.join(PUBLIC_DIR, relative))
      .then((info) => info.size)
      .catch(() => 0);

  /* Filenames are stable across rebuilds, so a CDN or the Next image optimizer
     would happily keep serving the render it cached before the copy changed.
     Stamping the content hash onto the URL makes a changed file a new URL. */
  const versioned = async (relative) => {
    const digest = await readFile(path.join(PUBLIC_DIR, relative))
      .then((data) => createHash("sha256").update(data).digest("hex").slice(0, 8))
      .catch(() => null);
    return digest ? `${relative}?v=${digest}` : relative;
  };

  const posts = await Promise.all(
    concepts.map(async (concept) => ({
      id: concept.id,
      title: concept.title,
      note: concept.note,
      headline: concept.headline ?? concept.quote ?? "",
      renditions: await Promise.all(
        SIZES.map(async (size) => {
          const base = `/social/${concept.id}-${size.id}`;
          return {
            sizeId: size.id,
            label: size.label,
            width: size.width,
            height: size.height,
            png: await versioned(`${base}.png`),
            jpg: await versioned(`${base}.jpg`),
            mp4: await versioned(`${base}.mp4`),
            pngBytes: await bytesOf(`${base}.png`),
            jpgBytes: await bytesOf(`${base}.jpg`),
            mp4Bytes: await bytesOf(`${base}.mp4`),
          };
        })
      ),
    }))
  );

  const body = `// Generated by scripts/social/generate.mjs. Do not edit by hand.
// Run \`pnpm social:build\` to regenerate.

export type SocialRendition = {
  sizeId: string;
  label: string;
  width: number;
  height: number;
  png: string;
  jpg: string;
  mp4: string;
  pngBytes: number;
  jpgBytes: number;
  mp4Bytes: number;
};

export type SocialPost = {
  id: string;
  title: string;
  note: string;
  headline: string;
  renditions: SocialRendition[];
};

export const MOTION_SECONDS = ${MOTION.seconds};

export const SOCIAL_POSTS: SocialPost[] = ${JSON.stringify(posts, null, 2)};
`;

  await writeFile(MANIFEST_PATH, body, "utf8");
}

async function buildRendition(chrome, concept, size) {
  const name = `${concept.id}-${size.id}`;
  const pngPath = path.join(OUT_DIR, `${name}.png`);

  const stillHtml = path.join(WORK_DIR, `${name}.html`);
  await writeFile(stillHtml, documentFor(concept, size), "utf8");
  await shoot(chrome, stillHtml, pngPath, size);
  const jpeg = await toJpeg(pngPath);

  /* Two plates feed the loop: everything but the cover, and the cover alone on
     a transparent frame. The loop paints its own bands, so neither carries
     the baked-in ones. */
  const layers = concept.markSub ? ["base", "cover", "mark"] : ["base", "cover"];
  const plates = {};
  for (const layer of layers) {
    const html = path.join(WORK_DIR, `${name}-${layer}.html`);
    plates[layer] = path.join(WORK_DIR, `${name}-${layer}.png`);
    await writeFile(
      html,
      documentFor(concept, size, { includeBands: false, layer }),
      "utf8"
    );
    await shoot(chrome, html, plates[layer], size, {
      transparent: layer !== "base",
    });
  }

  const loop = await renderLoop({
    basePlatePath: plates.base,
    coverPlatePath: plates.cover,
    markPlatePath: plates.mark ?? null,
    outPath: path.join(OUT_DIR, `${name}.mp4`),
    size,
    seed: seedFrom(`${name}-motion`),
  });

  console.log(
    `rendered ${name}: png${jpeg ? " jpg" : ""} mp4 (${loop.bursts} bursts)`
  );
}

async function main() {
  const chrome = findChrome();
  await rm(WORK_DIR, { recursive: true, force: true });
  await mkdir(WORK_DIR, { recursive: true });
  await mkdir(OUT_DIR, { recursive: true });

  const only = process.argv.slice(2);
  const concepts = only.length
    ? CONCEPTS.filter((concept) => only.some((arg) => concept.id.includes(arg)))
    : CONCEPTS;

  for (const concept of concepts) {
    for (const size of SIZES) {
      await buildRendition(chrome, concept, size);
    }
  }

  const expected = new Set(
    CONCEPTS.flatMap((concept) =>
      SIZES.flatMap((size) =>
        ["png", "jpg", "mp4"].map(
          (extension) => `${concept.id}-${size.id}.${extension}`
        )
      )
    )
  );
  const stale = await pruneStale(expected);
  stale.forEach((name) => console.log(`removed public/social/${name}`));

  await writeManifest(CONCEPTS);
  console.log(`wrote ${path.relative(ROOT, MANIFEST_PATH)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
